### PR TITLE
Change to vendor module

### PR DESCRIPTION
**Pull request by DorsetDigital**
Change to vendor module format to keep the root tidy :-)
Update to docs to use FQCN in yml example

### CODE REVIEW

**Comment by DorsetDigital** [comment]
Hi,
Is this something which is possible?  I've got a forked version that I'm using at the moment, but it would be good if there was a version available via packagist.

**Comment by altwohill** [comment]
Hi Damian, I'd be keen to see this too! 
Also, if you're too busy to maintain the module I'd be happy to help out.

**Comment by DorsetDigital** [comment]
> Also, if you're too busy to maintain the module I'd be happy to help out.

Likewise.  Always happy to pitch in where I can :-)

**Comment by tractorcow** [comment]
@DorsetDigital I've added you as contributor, and I've merged the other vendormodule PR.

**Comment by tractorcow** [comment]
@altwohill too

**Pull request closed without merging**
