### PR TITLE
[WIP] SilverStripe 4 Compatability

### PR DESCRIPTION
**Pull request by andrewandante**
Placeholder while I work it out

### CODE REVIEW

**Comment by andrewandante** [comment]
@tractorcow think we are there - have it working locally at least.

**Comment by tractorcow** [comment]
We probably shoudln't use `SilverStripe` as a top level namespace. It should be `TractorCow`, since it's a different vendor.

**Comment by andrewandante** [comment]
Fair enough. I have also just realised that the CachedTwitterService isn't
fixed at all (yay dev environments) so will re-apply the WIP tag.

**Comment by andrewandante** [comment]
OK @tractorcow ready for another swing at this

**Comment by tractorcow** [comment]
Merged manually with https://github.com/tractorcow/silverstripe-twitter/commit/6937f76d0c20a063827cb9b95f8e4dfbded79564

**Pull request closed without merging**
